name: Deploy addon to beamup

on:
  push:
    branches:
      - main

jobs:
  beamup-deploy:
    name: Deploy to beamup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install beamup
        run: npm install beamup-cli -g
      - name: Create beamup config
        env:
          BEAMUP_CONFIG_JSON: ${{ secrets.BEAMUP_CONFIG_JSON }}
        run: |
          touch ~/beamup-config.json
          echo "$BEAMUP_CONFIG_JSON" > ~/beamup-config.json
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add beamup host to known hosts
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: a.baby-beamup.club
      - name: Add beamup remote repository
        run: git remote add beamup ${{ vars.BEAMUP_REPO }}
      - name: Deploy addon to beamup
        run: git push beamup HEAD:master --force
