name: Deploy addon to beamup

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  beamup-deploy:
    name: Deploy to beamup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add beamup to known hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H a.baby-beamup.club >> ~/.ssh/known_hosts
      - name: Add beamup remote repository
        run: git remote add beamup ${{ vars.BEAMUP_REPO }}
      - name: Create env varriables
        env:
          KTUVIT_USER_EMAIL: ${{ secrets.KTUVIT_USER_EMAIL }}
          KTUVIT_USER_HASHED_PASSWORD: ${{ secrets.KTUVIT_USER_HASHED_PASSWORD }}
        run: |
          ssh dokku@a.baby-beamup.club config:set 4b139a4b7f94/ktuvit-stremio KTUVIT_USER_EMAIL="$KTUVIT_USER_EMAIL"
          ssh dokku@a.baby-beamup.club config:set 4b139a4b7f94/ktuvit-stremio KTUVIT_USER_HASHED_PASSWORD="$KTUVIT_USER_HASHED_PASSWORD"
      - name: Deploy addon to beamup
        run: |
          git config user.name "github-cd"
          git config user.email "cd@github.com"
          git commit --allow-empty -m "Beamup empty auto commit"
          git push beamup HEAD:master --force
